// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@idol-api.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/analytics/usage": {
            "get": {
                "description": "APIキー単位のAPI利用統計を返す（管理者専用）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "API利用サマリー取得",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 7,
                        "description": "集計期間（日数、デフォルト7、最大90）",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/export/idols": {
            "get": {
                "description": "全アイドルデータをJSON/JSONL形式でエクスポートする（管理者専用、レート制限あり）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "export"
                ],
                "summary": "アイドルエクスポート",
                "parameters": [
                    {
                        "type": "string",
                        "default": "json",
                        "description": "出力形式 (json|jsonl)",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/export/logs": {
            "get": {
                "description": "エクスポートの実行履歴を返す（管理者専用）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "export"
                ],
                "summary": "エクスポート実行履歴",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "件数上限（最大100、デフォルト50）",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/admin/jobs/bulk-import": {
            "post": {
                "description": "バルクインポートを非同期で実行するジョブをキューに追加する（管理者専用）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "バルクインポートジョブ作成",
                "parameters": [
                    {
                        "description": "インポートデータ",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.BulkImportRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/jobs/{id}": {
            "get": {
                "description": "指定したジョブのステータスと結果を返す（管理者専用）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "ジョブステータス取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ジョブID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.JobStatusDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/jobs/{id}/retry": {
            "post": {
                "description": "失敗したジョブを再実行する（管理者専用）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "ジョブリトライ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ジョブID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/webhooks": {
            "get": {
                "description": "Webhook購読一覧を返す（管理者専用）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Webhook購読一覧",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.SubscriptionResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "新しいWebhook購読を作成する（管理者専用）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Webhook購読作成",
                "parameters": [
                    {
                        "description": "購読設定",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.SubscriptionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/webhooks/{id}": {
            "delete": {
                "description": "Webhook購読を削除する（管理者専用）",
                "tags": [
                    "webhooks"
                ],
                "summary": "Webhook購読削除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "購読ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events": {
            "get": {
                "description": "条件を指定してイベント一覧を取得（検索・フィルタリング・ページネーション対応）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "イベント一覧取得",
                "parameters": [
                    {
                        "enum": [
                            "live",
                            "handshake",
                            "release",
                            "fan_meeting",
                            "online"
                        ],
                        "type": "string",
                        "description": "イベントタイプ",
                        "name": "event_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "開始日FROM (YYYY-MM-DD)",
                        "name": "start_date_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "開始日TO (YYYY-MM-DD)",
                        "name": "start_date_to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "会場ID",
                        "name": "venue_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "パフォーマーID",
                        "name": "performer_id",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "タグ（複数可）",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "start_date_time",
                            "created_at"
                        ],
                        "type": "string",
                        "default": "start_date_time",
                        "description": "ソート項目",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "asc",
                        "description": "ソート順",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "ページ番号",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "1ページあたりの件数",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/event.SearchResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "新しいイベント/ライブを作成する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "イベント作成",
                "parameters": [
                    {
                        "description": "イベント作成リクエスト",
                        "name": "event",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/event.CreateEventCommand"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/event.EventDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events/{id}": {
            "get": {
                "description": "IDを指定してイベント情報を取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "イベント詳細取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "イベントID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/event.EventDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/idols": {
            "get": {
                "description": "条件を指定してアイドル一覧を取得（検索・フィルタリング・ページネーション対応）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idols"
                ],
                "summary": "アイドル一覧取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "名前（部分一致）",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "事務所ID",
                        "name": "agency_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最小年齢",
                        "name": "age_min",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最大年齢",
                        "name": "age_max",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "生年月日FROM (YYYY-MM-DD)",
                        "name": "birthdate_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "生年月日TO (YYYY-MM-DD)",
                        "name": "birthdate_to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "関連データ読み込み (カンマ区切り: agency,groups)",
                        "name": "include",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "name",
                            "birthdate",
                            "created_at"
                        ],
                        "type": "string",
                        "default": "created_at",
                        "description": "ソート項目",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "ソート順",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "ページ番号",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "1ページあたりの件数",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/idol.SearchResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "新しいアイドルを作成する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idols"
                ],
                "summary": "アイドル作成",
                "parameters": [
                    {
                        "description": "アイドル作成リクエスト",
                        "name": "idol",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateIdolRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/idol.IdolDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/idols/bulk": {
            "post": {
                "description": "複数のアイドルを一括作成する（write認証必須、最大500件）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idols"
                ],
                "summary": "アイドル一括作成",
                "parameters": [
                    {
                        "description": "バルク作成リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.BulkCreateIdolsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/idol.BulkResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/idols/{id}": {
            "get": {
                "description": "IDを指定してアイドル情報を取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idols"
                ],
                "summary": "アイドル詳細取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "アイドルID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "関連データ読み込み (カンマ区切り: agency,groups)",
                        "name": "include",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/idol.IdolDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "IDを指定してアイドル情報を更新する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idols"
                ],
                "summary": "アイドル更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "アイドルID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "アイドル更新リクエスト",
                        "name": "idol",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateIdolRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "IDを指定してアイドルを削除する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idols"
                ],
                "summary": "アイドル削除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "アイドルID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/idols/{id}/duplicate-candidates": {
            "get": {
                "description": "指定したアイドルの重複候補を返す（管理者専用）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idols"
                ],
                "summary": "重複候補取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "アイドルID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/idol.DuplicateCandidateDTO"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/idols/{id}/external-ids": {
            "get": {
                "description": "アイドルの外部サービスIDマッピングを取得する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idols"
                ],
                "summary": "外部IDマッピング取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "アイドルID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "アイドルの外部サービスIDマッピングを更新する（write認証必須）。空文字列を指定した場合は該当IDを削除。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idols"
                ],
                "summary": "外部IDマッピング更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "アイドルID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "外部IDマッピング",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateExternalIDsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/idols/{id}/restore": {
            "put": {
                "description": "削除されたアイドルを復元する（管理者専用）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idols"
                ],
                "summary": "アイドル復元",
                "parameters": [
                    {
                        "type": "string",
                        "description": "アイドルID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/idols/{id}/social-links": {
            "put": {
                "description": "アイドルのSNS/外部リンク情報を更新する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "idols"
                ],
                "summary": "SNS/外部リンク更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "アイドルID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "SNS/外部リンク更新リクエスト",
                        "name": "social_links",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/idol.UpdateSocialLinksCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tags": {
            "get": {
                "description": "条件を指定してタグ一覧を取得（検索・フィルタリング・ページネーション対応）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "タグ一覧取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "タグ名（部分一致）",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "genre",
                            "region",
                            "style",
                            "other"
                        ],
                        "type": "string",
                        "description": "カテゴリ",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "ページ番号",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "1ページあたりの件数",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tag.SearchResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "新しいタグを作成する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "タグ作成",
                "parameters": [
                    {
                        "description": "タグ作成リクエスト",
                        "name": "tag",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tag.CreateTagCommand"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/tag.TagDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tags/{id}": {
            "get": {
                "description": "IDを指定してタグ情報を取得する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "タグ詳細取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "タグID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tag.TagDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "IDを指定してタグ情報を更新する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "タグ更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "タグID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "タグ更新リクエスト",
                        "name": "tag",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tag.UpdateTagCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "IDを指定してタグを削除する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "タグ削除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "タグID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "event.CreateEventCommand": {
            "type": "object",
            "required": [
                "event_type",
                "start_date_time",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "end_date_time": {
                    "description": "RFC3339形式（オプション）",
                    "type": "string"
                },
                "event_type": {
                    "type": "string"
                },
                "official_url": {
                    "type": "string"
                },
                "performer_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "start_date_time": {
                    "description": "RFC3339形式",
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ticket_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "venue_id": {
                    "type": "string"
                }
            }
        },
        "event.EventDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_date_time": {
                    "type": "string"
                },
                "event_type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "official_url": {
                    "type": "string"
                },
                "performer_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "start_date_time": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ticket_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "venue_id": {
                    "type": "string"
                }
            }
        },
        "event.PaginationLinks": {
            "type": "object",
            "properties": {
                "first": {
                    "type": "string"
                },
                "last": {
                    "type": "string"
                },
                "next": {
                    "type": "string"
                },
                "prev": {
                    "type": "string"
                }
            }
        },
        "event.PaginationMeta": {
            "type": "object",
            "properties": {
                "has_next": {
                    "type": "boolean"
                },
                "has_prev": {
                    "type": "boolean"
                },
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "event.SearchResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/event.EventDTO"
                    }
                },
                "links": {
                    "$ref": "#/definitions/event.PaginationLinks"
                },
                "meta": {
                    "$ref": "#/definitions/event.PaginationMeta"
                }
            }
        },
        "handlers.BulkCreateIdolsRequest": {
            "type": "object",
            "required": [
                "idols"
            ],
            "properties": {
                "idols": {
                    "type": "array",
                    "maxItems": 500,
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "required": [
                            "name"
                        ],
                        "properties": {
                            "agency_id": {
                                "type": "string"
                            },
                            "birthdate": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string",
                                "maxLength": 100,
                                "minLength": 1
                            }
                        }
                    }
                }
            }
        },
        "handlers.BulkImportItem": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "agency_id": {
                    "type": "string"
                },
                "aliases": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "birthdate": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tag_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handlers.BulkImportRequest": {
            "type": "object",
            "required": [
                "items"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "maxItems": 1000,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/handlers.BulkImportItem"
                    }
                }
            }
        },
        "handlers.CreateIdolRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "agency_id": {
                    "type": "string"
                },
                "aliases": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "birthdate": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                }
            }
        },
        "handlers.CreateSubscriptionRequest": {
            "type": "object",
            "required": [
                "events",
                "url"
            ],
            "properties": {
                "events": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "handlers.JobStatusDTO": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "error_msg": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "job_type": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "handlers.SubscriptionResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "events": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "secret": {
                    "description": "作成時のみ返す",
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "handlers.UpdateExternalIDsRequest": {
            "type": "object",
            "required": [
                "external_ids"
            ],
            "properties": {
                "external_ids": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "handlers.UpdateIdolRequest": {
            "type": "object",
            "properties": {
                "agency_id": {
                    "type": "string"
                },
                "aliases": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "birthdate": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                }
            }
        },
        "idol.BulkError": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "idol.BulkResult": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/idol.IdolDTO"
                    }
                },
                "error_count": {
                    "type": "integer"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/idol.BulkError"
                    }
                },
                "success_count": {
                    "type": "integer"
                }
            }
        },
        "idol.DuplicateCandidateDTO": {
            "type": "object",
            "properties": {
                "idol": {
                    "$ref": "#/definitions/idol.IdolDTO"
                },
                "reason": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                }
            }
        },
        "idol.IdolDTO": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "agency": {
                    "description": "include=agency時に展開"
                },
                "agency_id": {
                    "type": "string"
                },
                "aliases": {
                    "description": "別名一覧（多言語・旧名）",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "birthdate": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "external_ids": {
                    "description": "外部サービスIDマッピング",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "social_links": {
                    "description": "SNS/外部リンク"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "idol.PaginationLinks": {
            "type": "object",
            "properties": {
                "first": {
                    "type": "string"
                },
                "last": {
                    "type": "string"
                },
                "next": {
                    "type": "string"
                },
                "prev": {
                    "type": "string"
                }
            }
        },
        "idol.PaginationMeta": {
            "type": "object",
            "properties": {
                "has_next": {
                    "type": "boolean"
                },
                "has_prev": {
                    "type": "boolean"
                },
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "idol.SearchResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/idol.IdolDTO"
                    }
                },
                "links": {
                    "$ref": "#/definitions/idol.PaginationLinks"
                },
                "meta": {
                    "$ref": "#/definitions/idol.PaginationMeta"
                }
            }
        },
        "idol.UpdateSocialLinksCommand": {
            "type": "object",
            "properties": {
                "facebook": {
                    "type": "string"
                },
                "fan_club": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "instagram": {
                    "type": "string"
                },
                "official_website": {
                    "type": "string"
                },
                "tiktok": {
                    "type": "string"
                },
                "twitter": {
                    "type": "string"
                },
                "youtube": {
                    "type": "string"
                }
            }
        },
        "middleware.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "tag.CreateTagCommand": {
            "type": "object",
            "required": [
                "category",
                "name"
            ],
            "properties": {
                "category": {
                    "type": "string",
                    "enum": [
                        "genre",
                        "region",
                        "style",
                        "other"
                    ]
                },
                "description": {
                    "type": "string",
                    "maxLength": 200
                },
                "name": {
                    "type": "string",
                    "maxLength": 50
                }
            }
        },
        "tag.PaginationLinks": {
            "type": "object",
            "properties": {
                "first": {
                    "type": "string"
                },
                "last": {
                    "type": "string"
                },
                "next": {
                    "type": "string"
                },
                "prev": {
                    "type": "string"
                }
            }
        },
        "tag.PaginationMeta": {
            "type": "object",
            "properties": {
                "has_next": {
                    "type": "boolean"
                },
                "has_prev": {
                    "type": "boolean"
                },
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "tag.SearchResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tag.TagDTO"
                    }
                },
                "links": {
                    "$ref": "#/definitions/tag.PaginationLinks"
                },
                "meta": {
                    "$ref": "#/definitions/tag.PaginationMeta"
                }
            }
        },
        "tag.TagDTO": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "tag.UpdateTagCommand": {
            "type": "object",
            "required": [
                "category",
                "name"
            ],
            "properties": {
                "category": {
                    "type": "string",
                    "enum": [
                        "genre",
                        "region",
                        "style",
                        "other"
                    ]
                },
                "description": {
                    "type": "string",
                    "maxLength": 200
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 50
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Idol API",
	Description:      "包括的アイドル情報API - アイドル、グループ、事務所、イベント情報を提供",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
